---
name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Set up Python 3.13
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: "3.13"
      - name: Install Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev
      - name: Test
        run: |
          pipenv run test
      - name: Typecheck
        run: |
          pipenv run typecheck
      - name: Stylecheck
        run: |
          pipenv run stylecheck
      - name: Lint
        run: |
          pipenv run pre-commit-fix
      - name: Format
        run: |
          pipenv run pre-commit-format
